### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by SDavisMedia** [SDavisMedia/udshow-site#2]
We needs one.

**Comment by SDavisMedia** [comment]
@donlyons @dewanemutunga What do y'all think about this as _the most basic version_ of the logo.

![ud-show-logo-black-small](https://user-images.githubusercontent.com/2359131/28747274-bf2765a2-744f-11e7-93d5-e10f1abe4ddf.png)

**Comment by DewaneMutunga** [comment]
I'm cool with this for now. I don't this it's something we should get too hung up on at this point.

**Comment by donlyons** [comment]
Yea i agree... nice and simple, lets rock with it.

**Comment by SDavisMedia** [comment]
Deal.
